# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx/Projects/abacus/abacus.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/Projects/abacus/abacus.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Binary_to_BCD_B_bcdout.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/multi_4_4_pp1.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Display_QU.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/multi_4_4_pp2.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/multi_4_4_pp3.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Binary_to_BCD_B1_bcdout1.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Divider.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/multi_4_4_pp0.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Adder_Subtractor.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Binary_to_BCD_B2_bcdout2.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Seg_7_Display.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Display_REM.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Segment_Scroll.v
  D:/Xilinx/Projects/abacus/abacus.srcs/sources_1/imports/Abacus_Verilog_SrcFiles/Basys3_Abacus_Top.v
}
read_xdc D:/Xilinx/Projects/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/Xilinx/Projects/Basys3_Master.xdc]

synth_design -top Basys3_Abacus_Top -part xc7a35tcpg236-1
write_checkpoint -noxdef Basys3_Abacus_Top.dcp
catch { report_utilization -file Basys3_Abacus_Top_utilization_synth.rpt -pb Basys3_Abacus_Top_utilization_synth.pb }
